# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IKHfSt5YVbEVj0EF_dR6hrc--l-Ly2q6
"""

##James-Lawrence Weigelt

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
!pip install geopandas
import geopandas as gpd

data = pd.read_csv("https://data.cdc.gov/api/views/95ax-ymtc/rows.csv?accessType=DOWNLOAD")
data.shape
data.describe(include='all')

data.describe(include='float64')
data

from matplotlib import pyplot as plt
data['STUB_LABEL_NUM'].plot(kind='hist', bins=20, title='STUB_LABEL_NUM')
plt.gca().spines[['top', 'right',]].set_visible(False)

plot1= data.query('STUB_LABEL_NUM < 1.1')
plot1.shape

y= plot1['ESTIMATE']
x= plot1['YEAR']
print(x)
print(y)

y= plot1['ESTIMATE']
x= plot1['YEAR']

plt.scatter(x, y, label="line L", color='#4a412a') #data displayer

plt.xlabel("Year")
plt.ylabel("Deaths")
plt.title("Deaths/Year")
plt.show()